---
abstract: ~
author:
  - 'This code is maintained by the Monitoring Plugin Development Team: see'
  - 'Monitoring Plugin Team <devel@monitoring-plugins.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Monitoring-Plugin
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor: 0
  Config::Tiny: 0
  File::Basename: 0
  File::Spec: 0
  IO::File: 0
  Math::Calc::Units: 0
  Params::Validate: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/monitoring-plugins/monitoring-plugin-perl
version: 0.37
